name = "quickchart"
main = "src/index.ts"
compatibility_date = "2024-11-19"
account_id = "96d18c881e62ba88acd99585849442ae"

# Cloudflare Workers configuration
workers_dev = true

# KV namespace for caching
[[kv_namespaces]]
binding = "CHART_CACHE"
id = "1a3cb5eb4e7843db81c020e70a4da321"

[vars]
CACHE_TTL = "864000"  # 10 days
MAX_WIDTH = "2000"
MAX_HEIGHT = "2000"
